spring:
  datasource:
    url: jdbc:mysql://rm-wz9to6ca16n6999d1so.mysql.rds.aliyuncs.com:3306/talentcode_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:
    password:
